spring:
  application:
    name: tinder
  datasource:
    url: jdbc:postgresql://localhost:5433/tinder
    username: postgres
    password: saintitmo336204
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org.springframework.security.web: DEBUG
    org:
      hibernate:
        type: TRACE
        SQL: DEBUG
    org.springframework.data.jpa: DEBUG
